server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dachuang
    password: Dq123456789.
    url: jdbc:mysql://172.17.59.93:3306/first

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dq.domain

